# **NumPy & SciPy**

**NumPy and SciPy** are powerful libraries for mathematics,
science and engineering computing including data analysis.

● **NumPy** provides Core Data Structure libraries
– http://www.numpy.org/

● **SciPy** provides Scientific Algorithm libraries
– http://scipy.org/

● Documentation about NumPy and Scipy
– http://docs.scipy.org/doc/numpy/


### **Finding Documentation**

In [2]:
import numpy as np
import scipy as sp

In [3]:
np.info()

 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP
   polyval(p, x)
 

In [4]:
sp.info()

 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP
   polyval(p, x)
 

/var/folders/gp/2fjqrh9x7xxb3vsdhj8sqp240000gn/T/ipykernel_97907/1334206754.py:1: DeprecationWarning: scipy.info is deprecated and will be removed in SciPy 2.0.0, use numpy.info instead
  sp.info()


## **NumPy**

**Mathematical Computation with Numpy**

Numpy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

Main numpy website is the following:

https://numpy.org/

You can find numpy tutorial and documentations here

https://numpy.org/doc/stable/

If you are new to numpy, then start with the following quick start guide

https://numpy.org/doc/stable/user/quickstart.html

### **Importing NumPy**

In [65]:
# first install and import the numpy 

# if you have not installed it already, you can use pip install to do it. 

# !pip install numpy

# You only need to install it once on your machine. Comment out the above line if you have already installed numpy. 
# Then import it
import numpy as np

In [6]:
np.array

<function numpy.array>

### **Arrays in NumPy**

In [7]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [8]:
a.size # Cardinality

4

In [9]:
a.shape # Returns tuple listing length of array along each dimension of it

(4,)

In [10]:
a.ndim # Number of dimensions

1

In [11]:
type(a) 

numpy.ndarray

In [12]:
a.dtype # Type of Elements

dtype('int64')

In [13]:
a.itemsize # Bytes per Elements

8

In [14]:
a.nbytes # Returns number of bytes

32

### **Creating Arrays**

In [15]:
a = np.array([1, 4, 5, 8], float) # Creating an Array including float numbers
a

array([1., 4., 5., 8.])

**arange**

numpy.arange([start, ] stop,[step, ]dtype=None)


In [16]:
# arange
np.arange(3)

array([0, 1, 2])

In [17]:
np.arange(3.0)


array([0., 1., 2.])

In [18]:
np.arange(3,7)

array([3, 4, 5, 6])

In [19]:
np.arange(3,7,2)

array([3, 5])

**linspace**

numpy.linspace (start, stop, num=50, endpoint=True, retstep=False, dtype=None)


In [20]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [21]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [22]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [23]:
# numpy.linspace (start, stop, num=50, endpoint=True, retstep=False, dtype=None)
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

### **Operations on Arrays**

**Simple Operations on Arrays**

In [66]:
a =np.arange(1,5)
b =np.ones(4)
print(b) 
c = a + b 
c

[1. 1. 1. 1.]


array([2., 3., 4., 5.])

In [24]:
a = np.array([1,2,3,4])
b = a+a
b

array([2, 4, 6, 8])

In [25]:
c = a*a
c

array([ 1,  4,  9, 16])

In [26]:
d = a**a

**Simple Math Functions**

In [27]:
x = 2
y = x + a
y

array([3, 4, 5, 6])

In [28]:
y = x*a
y

array([2, 4, 6, 8])

In [29]:
y = np.sin(a)
y

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [64]:
# see
help(np.sin)

Help on ufunc object:

sin = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

**In-Place Operations**

What is in-place?
If you want to apply mathematical operations to a numpy array in-place, you can simply use the standard in-place operators +=, -=, /=, etc. So for example:

In [67]:
# Let us define a function add_10
def add_10(a):
    a += 10

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
add_10(a)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [30]:
x = np.arange(6.0)
z = 2 * np.pi
x *= z
x

array([ 0.        ,  6.28318531, 12.56637061, 18.84955592, 25.13274123,
       31.41592654])

### **Setting Array Elements - Filling Arrays**

In [72]:
# Indexing
a = np.array([1,2,3,4])
a[0]

1

In [75]:
# Setting Values
a[0] = 2 * 3
a[0]
a

array([6, 2, 3, 4])

In [33]:
# Fill - Fill the array with a scalar value
a.fill(0)
a

array([0, 0, 0, 0])

**Data types are important**

In [34]:
a.dtype

dtype('int64')

In [35]:
a[0] = 2.34
a

array([2, 0, 0, 0])

In [36]:
a.fill(2.3)
a

array([2, 2, 2, 2])

**Filling by using a slice**

In [37]:
a[:] = 1
a

array([1, 1, 1, 1])

### **Slicing Arrays**

Slicing can extract a portion of an
array by using a lower and upper
bound.

var[lower:upper:step]

In [38]:
a = np.array([3,21,1,6,7])
a[1:3]

array([21,  1])

In [39]:
# Negative Indexes
a[1:-2] 

array([21,  1])

In [40]:
# Omitting Indices: start or end or both
a[:2]

array([ 3, 21])

In [41]:
# Slicing With Steps
a[::2] # elements with even indexes

array([3, 1, 7])

### **N-Dimensional Arrays**

**2-D array**

In [42]:
b = np.array([[ 10, 11, 12, 13], [20, 21, 22, 23] ])
b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [43]:
b.shape 

(2, 4)

In [44]:
b.size

8

In [45]:
b.ndim # Number of dimensions

2

In [46]:
# Indexing in 2-D
b[1,3]

23

In [47]:
# Setting Values
b[1,3] = 2.3
b

array([[10, 11, 12, 13],
       [20, 21, 22,  2]])

In [48]:
# Addressing the rows using single index
b[1]

array([20, 21, 22,  2])

### **Advanced Indexing**

In [49]:
# Indexing by using positions
a = np.arange(10,40,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [50]:
indexes = np.array([1,3,-4])
x = a[indexes]
x

array([12, 16, 32])

In [51]:
# Indexing with Booleans
b = a[:5]
mymask = np.array([1,0,1,1,1],dtype=bool)
y = b[mymask]
y

array([10, 14, 16, 18])

In [52]:
# Create a mask by condition
under20 = a<20
under20

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False])

In [53]:
y = a[under20]
y

array([10, 12, 14, 16, 18])

### **Where Method - Finding Indexes**

**Where:**
- finds indexes in array where expression is True

In [54]:
a = np.array([ 1.19, 2.42, 3.91, 4.66])
a>2

array([False,  True,  True,  True])

In [55]:
np.where(a>2)

(array([1, 2, 3]),)

**Where 2-D**

In [56]:
a = np.array([[0,1,2,3], [4,5,6,7]])
a > 2

array([[False, False, False,  True],
       [ True,  True,  True,  True]])

In [57]:
np.where(a>2)
# Returns corresponding array([rows]), array([columns])
    # [0,3], [1,:]

(array([0, 1, 1, 1, 1]), array([3, 0, 1, 2, 3]))

In [58]:
a[np.where(a > 2)]

array([3, 4, 5, 6, 7])

In [76]:
help(np.where)

Help on function where in module numpy:

where(...)
    where(condition, [x, y], /)
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x an

### **Reshaping Arrays**

In [59]:
a = np.arange(10)
a.shape

(10,)

In [60]:
a.shape = (2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
a.shape = (2,1,5)
a

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

**Reshape - Returns a new array from the original array**

In [62]:
b = a.reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [63]:
# Reshape do not remove elements
a.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

### **Flatten Arrays and Flat Attribute**

**Flatten()**

Converts Multidimensional arrays into one
dimensional array

In [ ]:
np.array([[0, 1],
    [2, 3],
    [4, 5],
    [6, 7],
    [8, 9]])
b = a.flatten()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Attribute - flat**

a.flat is an attribute that can be used like an iterator to
access elements in a N-D array as one dimensional array.

In [ ]:
a = np.arange(10)
a.shape = (5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
b = a.flat
b[2] = 100
a

array([[  0,   1],
       [100,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9]])

### **Array Transpose**

In [ ]:
a = np.array([[0, 1, 2, 3, 4],
[5, 6, 7, 8, 9]])
a.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

- Strides are Tuple of bytes to
step in each dimension
- 8 bytes (1 value) to move to the
next column, but 40 bytes (5
values) to get to the same
position in the next row.
- Transpose only changes the
values of "Strides" in the array
memory.

In [ ]:
a.strides

(40, 8)

In [ ]:
a.T.strides

(8, 40)

### **Array Calculation Methods**

In [ ]:
# Sum - sum of the elements
a= np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.sum(a)


45

In [ ]:
# Sum along the axis
a = np.array([[0, 1],
    [2, 3],
    [4, 5],
    [6, 7],
    [8, 9]])
np.sum(a,axis = 0) # sums columns

array([20, 25])

In [ ]:
np.sum(a, axis = 1) # sums rows

array([ 1,  5,  9, 13, 17])

In [ ]:
# Product - calculate products of columns
a = np.array([[0, 1],
    [2, 3],
    [4, 5],
    [6, 7],
    [8, 9]])
a.prod(axis = 0)

array([  0, 945])

In [ ]:
a.prod(axis = 1)

array([ 0,  6, 20, 42, 72])

In [77]:
a=np.arange(0,16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
b=np.array([2,5,1,9])
b

array([2, 5, 1, 9])

In [79]:
np.dot(a, b)

array([ 34, 102, 170, 238])

In [80]:
np.dot(b,b)

111

### **Dot Product**

### **Min/Max**

**Min - Find the minimum**


In [ ]:
a= np.array([[0, 1, 2, 3, 4],
[5, 6, 7, 8, 9]])
a.min(axis=0)

array([0, 1, 2, 3, 4])

In [ ]:
a.min(axis = 0) # min in each column

array([0, 1, 2, 3, 4])

In [ ]:
a.min(axis = 1) # min in each row

array([0, 5])

In [ ]:
# argmin - finding the index of Minimum element
a.argmin(axis=1) # index of min in each row


array([0, 0])

In [ ]:
a.argmin(axis = 0) # index of min in each column

array([0, 0, 0, 0, 0])

**Max - Find the maximum similar to min**

In [ ]:
a.max(axis = 0)

array([5, 6, 7, 8, 9])

In [ ]:
a.max(axis = 1)

array([4, 9])

In [ ]:
a.argmax(axis = 0)

array([1, 1, 1, 1, 1])

In [ ]:
a.argmax(axis = 1)

array([4, 4])

In [ ]:
# Diagonal - Extract the diagonal from the array
a.diagonal()

array([0, 6])

### **Statistics Array Methods**

In [ ]:
# Mean
a = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
a.mean(axis = 0) # of each column

array([4., 5., 6.])

In [ ]:
# Average (same as mean)
np.average(a, axis= 0)


array([4., 5., 6.])

In [ ]:
# Average with weights
np.average(a, weights = [1,2,4], axis = 0)

array([5.28571429, 6.28571429, 7.28571429])

In [ ]:
# Standard Deviation
a.std(axis = 0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
a.std(axis = 0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
# Variance
a.var(axis = 0)

array([6., 6., 6.])

In [ ]:
a.var(axis = 1)

array([0.66666667, 0.66666667, 0.66666667])

### **Further Useful Array Methods**


**Clip – limit the values in an array.**

In [ ]:
a = np.array([20, 21, 22, 23, 24, 25, 26, 27, 28])

In [ ]:
a.clip(22,27)

array([22, 22, 22, 23, 24, 25, 26, 27, 27])

**Rounding Float Numbers**

In [ ]:
a = np.array([1.19, 2.42, 3.91, 4.66])
a.round()

array([1., 2., 4., 5.])

In [ ]:
a.round(decimals = 1)

array([1.2, 2.4, 3.9, 4.7])

## **SciPy**

Toolboxes dedicated to scientific computing.

http://scipy.org/

Scipy Tutorial

- http://docs.scipy.org/doc/scipy/reference/tutorial/index.html

- https://lectures.scientific-python.org/

### **Linear Algebra (scipy.linalg)**

● Functions related to Linear Algebra

● scipy.linalg includes all the functions in numpy.linalg plus some
other advances functions.

● A very good reference is:
- http://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html

● Basic routines:
- Finding Inverse - linalg.inv
- Solving linear system - linalg.solve
- Finding Determinant - linalg.det

### **Linear Algebra (scipy.linalg) - Examples**

In [ ]:
# Inverse of a Matrix
import numpy as np
from scipy import linalg
A = np.array([[1,2],[3,4]])
linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
A.dot(linalg.inv(A))

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [ ]:
# Rounding Float Numbers
A = np.array([[1,2],[3,4]])
B = np.array([[5],[6]])
np.linalg.solve(A,B)

array([[-4. ],
       [ 4.5]])

### **Sparse Matrices (scipy.sparse)¶**
● SciPy 2-D sparse matrix package for numeric data.
- https://docs.scipy.org/doc/scipy/reference/sparse.html

**Sparse matrix classes**

● bsr_matrix(arg1[, shape, dtype, copy, blocksize]) Block Sparse Row matrix

● coo_matrix(arg1[, shape, dtype, copy]) A sparse matrix in COOrdinate format.

● csc_matrix(arg1[, shape, dtype, copy]) Compressed Sparse Column matrix

● csr_matrix(arg1[, shape, dtype, copy]) Compressed Sparse Row matrix

● dia_matrix(arg1[, shape, dtype, copy]) Sparse matrix with DIAgonal storage

● dok_matrix(arg1[, shape, dtype, copy]) Dictionary Of Keys based sparse matrix.

● lil_matrix(arg1[, shape, dtype, copy]) Row-based linked list sparse matrix

● spmatrix([maxprint]) This class provides a base class for all sparse matrices.


### **Compressed Sparse Column Matrix**
**scipy.sparse.csc_matrix**
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html#scipy.sparse.csc_matrix


In [ ]:
import numpy as np
from scipy.sparse import csc_matrix
csc_matrix((3, 4), dtype=np.int8).toarray()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [ ]:
row = np.array([0, 2, 2, 0, 1, 2])
col = np.array([0, 0, 1, 2, 2, 2])
data = np.array([1, 2, 3, 4, 5, 6])
csc_matrix((data, (row, col)), shape=(3, 3)).toarray()

array([[1, 0, 4],
       [0, 0, 5],
       [2, 3, 6]])

### **Statistics (scipy.stats)**
● A large number of probability distributions as well as a
growing library of statistical functions

● Distributions like: norm, bernoulli, poisson

● Statistical functions like:

- Stats: Return mean, variance
- PDF: Probability Density Function
- PPF: Percent Point Function (Inverse of CDF)

● Documentation and Tutorial
- Reference:
http://docs.scipy.org/doc/scipy/reference/stats.html
- http://docs.scipy.org/doc/scipy/reference/tutorial/stats.html
